plugins {
    id 'application'
}

dependencyLocking {
    lockAllConfigurations()
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

tasks.withType(JavaCompile).configureEach {
    options.release = 11
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.stripe:mpp-java:0.1.4'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.22.3'

    constraints {
        implementation 'org.bouncycastle:bcprov-jdk18on:1.86'
    }
}

application {
    mainClass = 'xyz.tempo.mpp.conformance.Adapter'
}
