name: Dependency Scan

"on":
  pull_request:

permissions: {}

jobs:
  dependency-scan:
    uses: tempoxyz/gh-actions/.github/workflows/dependency-scan.yml@5e1c1d8d96398c49c836c10964038e10f9d071fc # 2026-10-03T06-17-35Z-5e1c1d8d
    permissions:
      contents: read
      id-token: write
